# Generated by Django 5.2.6 on 2025-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-submission_date']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='review_text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='submission_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
